package chimp.protocol

import io.circe.{Codec, Decoder, DecodingFailure, Encoder, Json}

import java.time.Instant
import scala.concurrent.duration.{DurationLong, FiniteDuration, NANOSECONDS}
import scala.util.Try

/** ISO-8601 duration codec for [[scala.concurrent.duration.FiniteDuration]], for example `"PT1H"` or `"PT1H30M"`. Encoding always produces
  * an ISO-8601 string. To interoperate with peers that send the bare-millisecond form, decoding also accepts a JSON number, read as
  * milliseconds. `java.time.Duration` is used internally only, as the JDK's ISO-8601 duration parser and formatter.
  */
object DurationCodecs:
  private def parseIso(iso: String): Either[String, FiniteDuration] =
    Try(java.time.Duration.parse(iso)).toEither.left
      .map(e => s"Invalid ISO-8601 duration '$iso': ${e.getMessage}")
      .map(d => FiniteDuration(d.toNanos, NANOSECONDS))

  private def formatIso(duration: FiniteDuration): String = java.time.Duration.ofNanos(duration.toNanos).toString

  given Codec[FiniteDuration] = Codec.from(
    Decoder.instance { c =>
      c.value.asString match
        case Some(iso) => parseIso(iso).left.map(message => DecodingFailure(message, c.history))
        case None      => c.as[Long].map(_.millis)
    },
    Encoder.encodeString.contramap(formatIso)
  )

import DurationCodecs.given

/** Identifier of a task, generated by the receiver with enough entropy to prevent enumeration. */
opaque type TaskId = String
object TaskId:
  def apply(value: String): TaskId = value
  extension (taskId: TaskId) def value: String = taskId
  given Codec[TaskId] = Codec.from(Decoder.decodeString, Encoder.encodeString)

/** The MCP Tasks extension (SEP-2663, identifier `io.modelcontextprotocol/tasks`): durable handles that let a receiver answer a request
  * with a task, which the requestor then polls and later collects the result of. Experimental; the wire format follows the reference
  * extension and may change.
  */
object TasksExtension:
  val Id: String = "io.modelcontextprotocol/tasks"

  /** `_meta` key under which a client declares its per-request capabilities. */
  val ClientCapabilitiesMetaKey: String = "io.modelcontextprotocol/clientCapabilities"

  /** The `_meta` entry a client adds to a request to declare support for the Tasks extension, so the server may answer with a task. */
  def clientCapabilityMeta: Map[String, Json] =
    Map(ClientCapabilitiesMetaKey -> Json.obj("extensions" -> Json.obj(Id -> Json.obj())))

  /** Whether the given request `_meta` declares support for the Tasks extension. */
  def declaredIn(meta: Option[Map[String, Json]]): Boolean =
    meta
      .flatMap(_.get(ClientCapabilitiesMetaKey))
      .flatMap(_.hcursor.downField("extensions").downField(Id).focus)
      .isDefined

/** State of a task. Terminal states are `Completed`, `Failed` and `Cancelled`. */
enum TaskStatus:
  case Working, InputRequired, Completed, Failed, Cancelled

object TaskStatus:
  private val toWire: Map[TaskStatus, String] = Map(
    Working -> "working",
    InputRequired -> "input_required",
    Completed -> "completed",
    Failed -> "failed",
    Cancelled -> "cancelled"
  )
  private val fromWire: Map[String, TaskStatus] = toWire.map((k, v) => v -> k)

  def isTerminal(status: TaskStatus): Boolean = status match
    case Completed | Failed | Cancelled => true
    case Working | InputRequired        => false

  given Encoder[TaskStatus] = Encoder.instance(status => Json.fromString(toWire(status)))
  given Decoder[TaskStatus] = Decoder.decodeString.emap(s => fromWire.get(s).toRight(s"Unknown task status: $s"))

/** Result returned when a receiver answers a request with a task instead of the request's normal result. */
final case class CreateTaskResult(
    taskId: TaskId,
    status: TaskStatus,
    createdAt: Option[Instant] = None,
    lastUpdatedAt: Option[Instant] = None,
    ttl: Option[FiniteDuration] = None,
    pollInterval: Option[FiniteDuration] = None,
    statusMessage: Option[String] = None,
    resultType: String = "task",
    _meta: Option[Map[String, Json]] = None
)

object CreateTaskResult:
  given Codec[CreateTaskResult] =
    Codec.forProduct9("taskId", "status", "createdAt", "lastUpdatedAt", "ttlMs", "pollIntervalMs", "statusMessage", "resultType", "_meta")(
      CreateTaskResult.apply
    )(r => (r.taskId, r.status, r.createdAt, r.lastUpdatedAt, r.ttl, r.pollInterval, r.statusMessage, r.resultType, r._meta))

final case class GetTaskParams(taskId: TaskId, _meta: Option[Map[String, Json]] = None) derives Codec
final case class GetTaskRequest(method: String = "tasks/get", params: GetTaskParams) derives Codec

/** Detailed task state returned by `tasks/get`. `result` is present once the task is `Completed`, `error` once it has `Failed`, and
  * `inputRequests` while it is `InputRequired`. `result` is left as raw JSON, since its shape depends on the request the task stands for.
  */
final case class GetTaskResult(
    taskId: TaskId,
    status: TaskStatus,
    createdAt: Option[Instant] = None,
    lastUpdatedAt: Option[Instant] = None,
    ttl: Option[FiniteDuration] = None,
    pollInterval: Option[FiniteDuration] = None,
    statusMessage: Option[String] = None,
    result: Option[Json] = None,
    error: Option[JSONRPCErrorObject] = None,
    inputRequests: Option[Map[String, Json]] = None,
    resultType: Option[String] = None,
    _meta: Option[Map[String, Json]] = None
)

object GetTaskResult:
  given Codec[GetTaskResult] = Codec.forProduct12(
    "taskId",
    "status",
    "createdAt",
    "lastUpdatedAt",
    "ttlMs",
    "pollIntervalMs",
    "statusMessage",
    "result",
    "error",
    "inputRequests",
    "resultType",
    "_meta"
  )(GetTaskResult.apply)(r =>
    (
      r.taskId,
      r.status,
      r.createdAt,
      r.lastUpdatedAt,
      r.ttl,
      r.pollInterval,
      r.statusMessage,
      r.result,
      r.error,
      r.inputRequests,
      r.resultType,
      r._meta
    )
  )

final case class CancelTaskParams(taskId: TaskId, _meta: Option[Map[String, Json]] = None) derives Codec
final case class CancelTaskRequest(method: String = "tasks/cancel", params: CancelTaskParams) derives Codec

final case class UpdateTaskParams(taskId: TaskId, inputResponses: Map[String, Json], _meta: Option[Map[String, Json]] = None) derives Codec
final case class UpdateTaskRequest(method: String = "tasks/update", params: UpdateTaskParams) derives Codec

/** Acknowledgement returned by `tasks/cancel` and `tasks/update`. */
final case class TaskAck(
    taskId: Option[TaskId] = None,
    status: Option[TaskStatus] = None,
    resultType: String = "complete",
    _meta: Option[Map[String, Json]] = None
) derives Codec

/** Notification pushed by a receiver that supports task subscriptions; carries the same fields as a `tasks/get` result. */
final case class TaskStatusNotification(
    method: String = "notifications/tasks",
    params: GetTaskResult
) derives Codec
